FROM waifu2x
RUN apt-get update && apt-get install -y python3-pip

COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

COPY . /root/bpmbot
WORKDIR /root/bpmbot

ENTRYPOINT ["/root/bpmbot/do_cache.sh"]
